name: hello-world
on:
  push:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install
        run: npm install cypress --save-dev
      
      - name: Run e2e tests on Chrome
        run: npm run e2e:chrome
