name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
        run: 'npm run e2e:chrome'
